tls:
  certificates:
    - certFile: /etc/traefik/ssl/atari-test-public-key.crt
      keyFile: /etc/traefik/ssl/atari-test-private-key.key

http:
  routers:
    dashboard:
      rule: Host(`itsidevfsd0024.xaas.epfl.ch`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      service: api@internal
    atari:
      rule: Host(`itsidevfsd0024.xaas.epfl.ch`)
      tls: {}
      service: atari
      entrypoints:
        - https
  services:
    atari:
      loadBalancer:
        servers:
        - url: http://meteor:3000
