---
- name: Ensure that atari repository is present
  git:
    repo: 'https://github.com/epfl-si/atari'
    dest: /srv/atari
    version: "master"
    force: yes

- name: Copy secrets from keybase
  copy:
    src: /keybase/team/epfl_atari/settings-test.json
    dest: /srv/atari/settings.json

- name: Ensure Traefik repository exists
  file:
    state: directory
    path: "{{ item }}"
    mode: '0755'
  with_items:
   - /srv/traefik/ssl/
   - /srv/traefik/config/

- name: Copy Traefik certificates from keybase
  copy:
    src: "{{ item }}"
    dest: /srv/traefik/ssl/
  with_items:
    - /keybase/team/epfl_atari/ssl/atari-test-public-key.crt
    - /keybase/team/epfl_atari/ssl/atari-test-private-key.key

- name: Template static Traefik configuration
  template:
    src: traefik-static.yml
    dest: /srv/traefik/traefik.yml

- name: Template dynamic Traefik configuration
  template:
    src: traefik-dynamic.yml
    dest: /srv/traefik/config/

- name: Start ATARI containers (it might take a while)
  docker_compose:
    project_src: /srv/atari
    state: present
    build: yes
    recreate: always
    nocache: no
    pull: yes
    files:
      - docker-compose-test.yml
  vars:
      ansible_python_interpreter: /bin/python3
