---
- name: Install Docker
  apt:
    name: docker.io
    state: latest
    update_cache: true

- name: Install Python Docker
  apt:
    name: python3-docker
    state: latest
    update_cache: true

- name: Install pip
  apt:
    name: python3-pip
    state: latest
    update_cache: true

- name: Install docker-compose python package
  ansible.builtin.pip:
    name: docker-compose

- name: Ensure that ATARI Git repository is present and up to date
  git:
    repo: 'https://github.com/epfl-si/atari'
    dest: /srv/atari
    version: "master"
    force: yes

- name: "Copy secrets from keybase ({{ inventory_mode }})"
  copy:
    src: "/keybase/team/epfl_atari/settings-{{ inventory_mode }}.json"
    dest: /srv/atari/settings.json

- name: Ensure Traefik repository exists
  file:
    state: directory
    path: "{{ item }}"
    mode: '0755'
  with_items:
   - /srv/traefik/ssl/
   - /srv/traefik/config/

- name: Copy Traefik certificates from keybase
  copy:
    src: "{{ item }}"
    dest: /srv/traefik/ssl/
  with_items:
    - /keybase/team/epfl_atari/ssl/atari_epfl_ch/atari_epfl_ch.crt
    - /keybase/team/epfl_atari/ssl/atari_epfl_ch/atari.key
    - /keybase/team/epfl_atari/ssl/atari_epfl_ch/DigiCertCA.crt

- name: Template static Traefik configuration
  template:
    src: traefik-static.yml
    dest: /srv/traefik/traefik.yml

- name: Template dynamic Traefik configuration
  template:
    src: traefik-dynamic.yml
    dest: /srv/traefik/config/

- name: Start ATARI containers (it might take a while)
  docker_compose:
    project_src: /srv/atari
    state: present
    build: yes
    recreate: always
    nocache: no
    pull: yes
    files:
      - "docker-compose.yml"
  vars:
    ansible_python_interpreter: /bin/python3
