global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG

api:
  insecure: true
  dashboard: true

providers:
  file:
    directory: /etc/traefik/config
    watch: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
  https:
    address: ":443"

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    # manualRouting: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5
    # entryPoint: metrics
